package geoanalytique.gui;

import javax.swing.*;
import javax.swing.table.*;


public class containerPropriete extends JPanel{

	/**
	 * 
	 */

	public containerPropriete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {

        jscrolChamp = new javax.swing.JScrollPane();
        jtableChamp = new javax.swing.JTable();
        annulerBtn = new javax.swing.JButton();
        validerBtn = new javax.swing.JButton();
       /* data =new Object [][] {
                {"nom","carre1"},
                {"Point1 x/y","2/2"},
                {"point2 x/y","2/6"},
                {"point3 x/y","6/6"},
                {"poit4 x/y", "6/2"}
            };
        tilte=new String [] {
                "champs", "Valeurs"
            };
        jtableChamp.setModel(new DefaultTableModel(data,tilte));
        jscrolChamp.setViewportView(jtableChamp);
	*/
        annulerBtn.setText("Annuler");
        annulerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerBtnActionPerformed(evt);
            }
        });

        validerBtn.setText("Valider");
        validerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProprieteContainerLayout = new javax.swing.GroupLayout(this);
        this.setLayout(panelProprieteContainerLayout);
        panelProprieteContainerLayout.setHorizontalGroup(
                panelProprieteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProprieteContainerLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelProprieteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelProprieteContainerLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(annulerBtn)
                            .addGap(18, 18, 18)
                            .addComponent(validerBtn))
                        .addComponent(jscrolChamp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );
            panelProprieteContainerLayout.setVerticalGroup(
                panelProprieteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelProprieteContainerLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jscrolChamp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelProprieteContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(annulerBtn)
                        .addComponent(validerBtn)))
        );


    }// </editor-fold>//GEN-END:initComponents

    private void validerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validerBtnActionPerformed

    private void annulerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton annulerBtn;
    public javax.swing.JScrollPane jscrolChamp;
    public javax.swing.JTable jtableChamp;
    public javax.swing.JButton validerBtn;
    public Object data[][];
    public String tilte[];
}
